### ISSUE TITLE
Google and Facebook authentication

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#10]
**Tasks**
- [x] Handle Google authentication and console.log the details on success.
- [ ] Write tests for Google authentication.
- [x] Handle Facebook authentication and console.log the details on success.
- [ ] Write tests for Facebook authentication
- [ ] Host the frontend app on Heroku

**Comment by Qudraty456** [comment]
How can it work?
