### ISSUE TITLE
Build the remaining static pages

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#11]
**Tasks**
- [x] Market place page.
- [x] Build the cart page.
- [ ] Build a checkout page.
- [ ] Build a product item page.
- [x] Build a user account profile.
- [x] Build a vendor account profile.
- [x] Setup testing with jest.
