### ISSUE TITLE
Fetch authentication endpoints on the frontend

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#12]
**Tasks**
- [ ] Install react-redux.
- [ ] Fetch login endpoint.
- [ ] Display relevant error on error.
- [ ] Fetch Register Page.
- [ ] Display relevant error on error.
