### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#2]
A user should be able to create an account on the platform and login.

**Tasks**
- [x] Create a [app.properties](https://github.com/BuildForSDG/.github/blob/master/app.properties) file in root of repo and fill details
- [x] Build wireframe prototypes for authentication pages
- [x] Setup ReactJS
- [ ] Build the register page
- [ ] Validate register input data
- [ ] Make register page responsive
- [ ] Build a login page
- [ ] Validate login input data
- [ ] Make login page responsive

**Additional Context**
branch `ft-authentication-pages`

**Comment by Dave-mash** [comment]
Redundant issue
