### ISSUE TITLE
Interfacing, image hosting and testing

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#25]
**Tasks**

- [ ] Display fetched data on frontend.
- [ ] Display relevant errors and success messages
- [ ] Setup image hosting
- [ ] Wire up product filters
- [ ] Optimise the site for production
- [ ] Begging testing with Jest
- [ ] Configure env variables
