### ISSUE TITLE
Authentication frontend

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#4]
**Feature Description**
A user should be able to create an account on the platform and login.

**Tasks**
- [x] Create a [app.properties](https://github.com/BuildForSDG/.github/blob/master/app.properties) file in root of repo and fill details
- [x] Build wireframe prototypes for authentication pages
- [x] Setup ReactJS
- [x] Build the register page
- [x] Validate register input data
- [x] Make register page responsive
- [x] Build a login page
- [x] Validate login input data
- [x] Make login page responsive
- [ ] Build a reset password modal
- [ ] Wire up Google register and login
- [ ] Wire up Facebook register and login
