### ISSUE TITLE
Build wireframes for remaining pages

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#8]
Create wireframes for remaining pages.

**Tasks**
- [x] Home page wireframe with responsive designs
- [x] Cart page wireframe with responsive designs
- [x] Profile page wireframe with responsive designs
