### ISSUE TITLE
Content writing and logo.

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-frontend#9]
**Tasks**
- [ ] Handle content writing for the overall application
- [ ] Build an appropriate logo
- [ ] Adding relevant information to the footer
